ARG POSTGRES_VERSION="16-alpine3.20"

FROM postgres:${POSTGRES_VERSION}

LABEL author="Tiagocode <santiagomm1997@gmail.com>"
LABEL mantainer="Tiagocode <santiagomm1997@gmail.com>"

CMD ["postgres"]

EXPOSE 5432