name: Deploy to tiagocode.com

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              
      - name: Trigger AWS CodeDeploy Deployment
        uses: sourcetoad/aws-codedeploy-action@v1
        with:
          codedeploy_name: ${{ vars.TIAGOCODE_PROJECT_NAME }}-app
          codedeploy_group: ${{ vars.TIAGOCODE_PROJECT_NAME }}-dg
          s3_bucket: ${{ vars.TIAGOCODE_PROJECT_NAME }}-bucket
          s3_folder: env-${{ vars.TIAGOCODE_PROJECT_NAME }}.com
